### ISSUE TITLE
node_modules in npm package causes some problems

### ISSUE THREAD

**Issue by derobiom** [TheKeithStewart/angular2-esri4-components#11]
I was getting the error below before delete the node_modules folder under {myproject}\node_modules\angular2-esri4-components\...

Was this included in npm by mistake?

This was not happening in the example project though..somehow I'm doing some extra static checking?

The error:

"ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported."

**Comment by TheKeithStewart** [comment]
@derobiom there were some issues with getting this error in an earlier version of this library while working with the Angular CLI.  I believe that it has been corrected though.  I am not getting this error anymore.

If you are still receiving the error can you please provide more information about your project so that I can reproduce the issue?

**Comment by derobiom** [comment]
I tested the npm install again and there are no problems so please disregard.  I think that I may have run npm install again but from a child directory and received another inadvertent "node_modules" folder that did not cause a problem until the production build did the static checking thingy.
